### PR TITLE
Update Antmaze and Pointmaze datasets

### PR DESCRIPTION
**Pull request by alexdavey**
This PR addresses two issues with the antmaze datasets:

- The observation shape inconsistency in some episodes, as described in [this issue](https://github.com/Farama-Foundation/Minari/issues/199). This only affects the `umaze` datasets.
- The info structure is not consistent, since some info keys are not available on the Ant reset step. This affects all the antmaze datasets.

The antmaze generation scripts have been updated to address this. In the new `v1` datasets, only the `{goal, success, qpos, qvel}` info keys are stored.

The new datasets are not identical (I believe due to differences in MuJoCo versions), but are qualitatively very similar:

| Dataset                        | Avg return | Num truncations | Success rate  | Avg velocity  |
| ------------------------------ | ---------- | --------------- | ------------- | ------------- |
| antmaze-large-diverse-v1 (v0)  | 500 (492)  | 1000 (1000)     | 84.0% (83.2%) | 0.048 (0.047) |
| antmaze-large-play-v1 (v0)     | 514 (507)  | 1000 (1000)     | 84.6% (83.0%) | 0.046 (0.046) |
| antmaze-medium-diverse-v1 (v0) | 454 (460)  | 1000 (1000)     | 82.7% (83.4%) | 0.051 (0.050) |
| antmaze-medium-play-v1 (v0)    | 630 (627)  | 1000 (1000)     | 87.1% (87.0%) | 0.034 (0.034) |
| antmaze-umaze-diverse-v1 (v0)  | 557 (560)  | 1430 (1433)     | 93.8% (94.0%) | 0.022 (0.022) |
| antmaze-umaze-v1 (v0)         | 438 (433)  | 1430 (1433)     | 91.7% (90.2%) | 0.040 (0.040) |

In addition, this PR includes the following minor changes:

- Moved the `requirements.txt` from the top level to the individual script directories, so that the requirements for each set of datasets can be pinned, to increase reproducibility.

- The check scripts have been updated to be compatible with all datasets, and a new script `download_and_check_all_remote.py` has been added that checks all of the datasets in the Farama servers.

- Updated the documentation.

### CODE REVIEW

**Review by younik — COMMENTED** [review]
Thank you for the changes, looks good!
Regarding [checks/download_and_check_all_remote.py](https://github.com/rodrigodelazcano/d4rl-minari-dataset-generation/pull/13/files#diff-cf3287e39945ae51c3aef8757d17377166da7cb7aeac075cca7ae4b845641e88), I think we should change to test the scripts, not the remote datasets (these are already tested in Minari)

**Comment by alexdavey** [comment]
Thank you for the review @younik !

I have added the checks to the `antmaze` and `minigrid` generation scripts. I have also removed `download_and_check_all_remote.py`.

**PS:** There appear to be issues with the current `Adroit` and `pointmaze` datasets (similar to the `antmaze` issues). I will create some issues shortly so that we can keep track of them.

**Comment by alexdavey** [comment]
I have updated the `pointmaze` scripts, which had the same issues as the `antmaze` datasets. I also added some missing seeding, to improve the reproducibility of `minigrid`/`pointmaze` (although `minigrid` does not need to be regenerated).

Comparison between `pointmaze-v1` and `pointmaze-v2`:

| Dataset                        | Avg return    | Num truncations | Success rate  | Avg velocity    |
| ------------------------------ | ------------- | --------------- | ------------- | --------------- |
| pointmaze-large-dense-v2 (v1)  | 24.7 (24.7)   | 3360 (3322)     | -             | 0.0371 (0.0372) |
| pointmaze-large-v2 (v1)        | 0.999 (0.998) | 3360 (3325)     | 99.9% (99.8%) | 0.0371 (0.0372) |
| pointmaze-medium-dense-v2 (v1) | 26.3 (26.1)   | 4752 (4765)     | -             | 0.0347 (0.0348) |
| pointmaze-medium-v2 (v1)       | 0.999 (0.999) | 4752 (4778)     | 99.9% (99.9%) | 0.0347 (0.0348) |
| pointmaze-open-dense-v2 (v1)   | 20.9 (20.8)   | 9525 (9637)     | -             | 0.0362 (0.0362) |
| pointmaze-open-v2 (v1)         | 0.999 (0.999) | 9525 (9609)     | 99.9% (99.9%) | 0.0362 (0.0362) |
| pointmaze-umaze-dense-v2 (v1)  | 18.4 (18.3)   | 13210 (13289)   | -             | 0.0338 (0.0338) |
| pointmaze-umaze-v2 (v1)        | 1.00 (1.00)   | 13210 (13289)   | 100% (100%)   | 0.0338 (0.0338) |

@younik please let me know if there are any remaining issues. I plan on making a separate PR for the `Adroit` dataset updates at a later date.

**Review by younik — APPROVED** [review]

**Comment by younik** [comment]
It looks good, thank you!
@alexdavey feel free to update the datasets on remote then

**Pull request merged**
